### ISSUE TITLE
Upstream Progress Tracker

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#654]
This issue will be used to track upstream progress. Our initial goal is to upstream the "core" or heavily used projects.

### Completed
- [x] GNU Make - completed

### In Progress
- [ ] Git - https://github.com/git/git/pull/1537 - @HarithaIBM 
- [ ] Less - https://github.com/gwsw/less/pull/464 (pending review) 
- [ ] Vim - PR created for initial changes: https://github.com/vim/vim/pull/13821
- [ ] Bash - Source changes upstreamed, pending test contributions (https://github.com/ZOSOpenTools/bashport/tree/main/dev-patches) - @IgorTodorovskiIBM 
- [ ] Autoconf - PR2/PR3 contributed back, PR1 pending - https://github.com/ZOSOpenTools/autoconfport/tree/main/patches
- [ ] vim - in progress
- [ ] Iconv - Most changes contributed back, some change still pending https://github.com/ZOSOpenTools/libiconvport/tree/main/dev-patches
- [ ] Perl - Initial changes upstreamed, several more to go: https://github.com/ZOSOpenTools/perlport/tree/main/patches/PR1
- [ ] Ncurses - Started communications with the community on ASCII_TERMINFO variable

### Not started
- [ ] Automake - is this patch still necessary https://github.com/ZOSOpenTools/automakeport/blob/main/patches/PR1/distdir.am.patch

If there's any others that we've partially upstreamed or are planning to upstream in the near future, please let me know and I'll add it to this list

**Comment by v1gnesh** [comment]
Will try to format this like [this](https://github.com/v1gnesh/v1gnesh/blob/main/README.md) later :stuck_out_tongue:

**Comment by IgorTodorovskiIBM** [comment]
Update on vim: https://github.com/vim/vim/pull/13821 - a couple of changes were accepted
